os: linux
dist: precise

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

sudo: required

addons:
  hostname: drmaa.travis-ci.org
  hosts:
    - localhost
    - localhost.localdomain
    - drmaa.travis-ci.org


notifications:
  email: false

cache: pip

# Install stuff
before_install:
  - travis/install_sge.sh
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
  - pip install --upgrade pip
install:
  - pip install python-coveralls
  - pip install nose-cov
  - python setup.py install

# Run test
script:
  - nosetests -d -v --with-cov --cov drmaa --cov-config .coveragerc --logging-level=DEBUG

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

