language: python
python:
  - 2.6
  - 2.7
  - 3.2

notifications:
  email: false

# Install stuff
before_install:
  - travis/install_sge.sh
  - export GRID_MAP_REDIS_PORT=12345
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
install:
  - python setup.py install

# Run test
script:
  - nosetests -d -v

